service: simple-sls-project-v2
frameworkVersion: '3'

custom:
  defaultStage: staging
  currentStage: ${opt:stage, self:custom.defaultStage}
  snsGetSalaryTopicName: &snsGetSalaryTopicName playground-serv-get-salary-${self:custom.currentStage}

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: true

functions:
  api:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    PushGetShipmentDelayedTopicName:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: *snsGetSalaryTopicName
        FifoTopic: false

plugins:
  - serverless-plugin-typescript