service: simple-sls-project

frameworkVersion: '3'

custom:
  defaultStage: staging
  currentStage: ${opt:stage, self:custom.defaultStage}
  snsGetSalaryTopicName: &snsGetSalaryTopicName playground-serv-get-salary-${self:custom.currentStage}

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: true
  stage: ${self:custom.currentStage}

functions:
  api:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
  # SNS Topic will get created automatically
    GetSalaryTopicName:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: *snsGetSalaryTopicName
        FifoTopic: false
    SomeGetSalarySqsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-get-salary-${self:provider.stage}
        VisibilityTimeout: 900
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt SomeGetSalarySqsQueueDeadLetterQueue.Arn
          maxReceiveCount: 5
    SomeGetSalarySqsQueueDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-get-salary-dlq-${self:provider.stage}
        VisibilityTimeout: 900
    SomeSalarySnsToSqsSubscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        Protocol: "sqs"
        TopicArn: !Ref GetSalaryTopicName
        Endpoint: !GetAtt SomeGetSalarySqsQueue.Arn

plugins:
  - serverless-plugin-typescript